project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Nutrients Tracking"
  author:
    - ChengHsin Chang (cc5211)
    - YiChen Chen (yc4562)
  repo-url: https://github.com/priscachang/NutriTrack
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    self-contained: true


